common.datasource:
  poolName: mysql-pool
  jdbcUrl: jdbc:mysql://localhost:3306/rate_limiter
  username: root
  password: admin1234
  connection-test-query: SELECT 1
  minimum-idle: 10
  validation-timeout: 30000
  register-mbeans: false
  maximum-pool-size: 15
